In [17]:
import plotly.plotly as py
import numpy as np
from plotly.graph_objs import *
py.sign_in('horrendous.git', '8vbgagde6d')

In [18]:
import plotly.plotly as py
from plotly.graph_objs import *
# auto sign-in with credentials or use py.sign_in()
trace1 = Scatter3d(
        x=[1,2,3],
        y=[3,4,5],
        z=[1,3,4]
    )
data = Data([trace1])
py.plot(data)

u'https://plot.ly/~horrendous.git/14'

In [11]:
x1 = y1 = np.arange(-1,1,0.4)
yt1 = x1[:,np.newaxis]
print np.shape(yt1)
print '***'
print yt1

(5, 1)
***
[[-1. ]
 [-0.6]
 [-0.2]
 [ 0.2]
 [ 0.6]]


In [12]:
print x1, '-->', np.shape(x1)
print y1, '-->', np.shape(y1)
print x1*y1, '-->', np.shape(x1*y1)

[-1.  -0.6 -0.2  0.2  0.6] --> (5,)
[-1.  -0.6 -0.2  0.2  0.6] --> (5,)
[ 1.    0.36  0.04  0.04  0.36] --> (5,)


In [13]:
print x1*yt1
print '***'
print

[[ 1.    0.6   0.2  -0.2  -0.6 ]
 [ 0.6   0.36  0.12 -0.12 -0.36]
 [ 0.2   0.12  0.04 -0.04 -0.12]
 [-0.2  -0.12 -0.04  0.04  0.12]
 [-0.6  -0.36 -0.12  0.12  0.36]]
***



In [14]:
x = y = np.arange(-5,5,0.1)
yt = x[:,np.newaxis]
z = np.cos(x*yt)+np.sin(x*yt)

In [15]:
%%capture
# capture to suppress help() output
# remeber you can always call help on Plotly objects
help(Surface)

In [16]:
# aquatic colorscale
cls=[[0, 'rgb(0,0,131)'], [0.125, 'rgb(0,60,170)'], [0.375, 'rgb(5,255,255)'], [0.625, 'rgb(255,255,0)'], [0.875, 'rgb(250,0,0)'], [1, 'rgb(128,0,0)']]

data = Data([ Surface( x=x, y=y, z=z, colorscale=cls ) ])

layout = Layout(
    title='waaaaves',
    autosize=True,
    scene=Scene( 
        zaxis=ZAxis(range=[-5, 5],autorange=False,nticks=10,gridcolor='rgb(255, 255, 255)',gridwidth=2,zerolinecolor='rgb(255, 255, 255)',zerolinewidth=2),
        xaxis=XAxis(nticks=10,gridcolor='rgb(255, 255, 255)',gridwidth=2,zerolinecolor='rgb(255, 255, 255)',zerolinewidth=2),   
        yaxis=YAxis(nticks=10,gridcolor='rgb(255, 255, 255)',gridwidth=2,zerolinecolor='rgb(255, 255, 255)',zerolinewidth=2),        
        bgcolor="rgb(244, 244, 248)"
    )
)

fig = Figure(data=data, layout=layout)

# As of Plotly's python package plotly-1.5.0
# 2d contours in 3d plots aren't supported, 
# but you can hack them in like this.
# Stayed tuned for updates.
contours = { 'z':{ 'show':True } }
fig['data'][0]['contours'] = contours

# validate = False prevents syntax checking that would complain about the 2d contour hack (see above)
py.iplot(fig, filename='waaaaves', validate=False)

AttributeError: '_MovedItems' object has no attribute 'urllib'