Consider the Gram–Schmidt process applied to the columns of the full column rank matrix 
$A=[\mathbf{a}_1, \cdots, \mathbf{a}_n]$, with inner product $\langle\mathbf{v},\mathbf{w}\rangle = \mathbf{v}^\top \mathbf{w}$ (or $\langle\mathbf{v},\mathbf{w}\rangle = \mathbf{v}^* \mathbf{w}$ for the complex case).

Define the projection:

$$
\mathrm{proj}_{\mathbf{e}}\mathbf{a}
= \frac{\left\langle\mathbf{e},\mathbf{a}\right\rangle}{\left\langle\mathbf{e},\mathbf{e}\right\rangle}\mathbf{e}
$$

then:

\begin{align}
 \mathbf{u}_1 &= \mathbf{a}_1,
  & \mathbf{e}_1 &= {\mathbf{u}_1 \over \|\mathbf{u}_1\|} \\
 \mathbf{u}_2 &= \mathbf{a}_2-\mathrm{proj}_{\mathbf{u}_1}\,\mathbf{a}_2,
  & \mathbf{e}_2 &= {\mathbf{u}_2 \over \|\mathbf{u}_2\|} \\
 \mathbf{u}_3 &= \mathbf{a}_3-\mathrm{proj}_{\mathbf{u}_1}\,\mathbf{a}_3-\mathrm{proj}_{\mathbf{u}_2}\,\mathbf{a}_3,
  & \mathbf{e}_3 &= {\mathbf{u}_3 \over \|\mathbf{u}_3\|} \\
 & \vdots &&\vdots \\
 \mathbf{u}_k &= \mathbf{a}_k-\sum_{j=1}^{k-1}\mathrm{proj}_{\mathbf{u}_j}\,\mathbf{a}_k,
  &\mathbf{e}_k &= {\mathbf{u}_k\over\|\mathbf{u}_k\|}
\end{align}

We can now express the \mathbf{a}_is over our newly computed orthonormal basis:


\begin{align}
 \mathbf{a}_1 &= \langle\mathbf{e}_1,\mathbf{a}_1 \rangle \mathbf{e}_1  \\
 \mathbf{a}_2 &= \langle\mathbf{e}_1,\mathbf{a}_2 \rangle \mathbf{e}_1
  + \langle\mathbf{e}_2,\mathbf{a}_2 \rangle \mathbf{e}_2 \\
 \mathbf{a}_3 &= \langle\mathbf{e}_1,\mathbf{a}_3 \rangle \mathbf{e}_1
  + \langle\mathbf{e}_2,\mathbf{a}_3 \rangle \mathbf{e}_2
  + \langle\mathbf{e}_3,\mathbf{a}_3 \rangle \mathbf{e}_3 \\
 &\vdots \\
 \mathbf{a}_k &= \sum_{j=1}^{k} \langle \mathbf{e}_j, \mathbf{a}_k \rangle \mathbf{e}_j
\end{align}
where $\langle\mathbf{e}_i,\mathbf{a}_i \rangle = \|\mathbf{u}_i\|$. 

This can be written in matrix form:

 A = Q R 
where:

Q = $\left[ \mathbf{e}_1, \cdots, \mathbf{e}_n\right] \qquad \text{and} \qquad$

$$
R = \begin{pmatrix}
\langle\mathbf{e}_1,\mathbf{a}_1\rangle & \langle\mathbf{e}_1,\mathbf{a}_2\rangle &  \langle\mathbf{e}_1,\mathbf{a}_3\rangle  & \ldots \\
0                & \langle\mathbf{e}_2,\mathbf{a}_2\rangle                        &  \langle\mathbf{e}_2,\mathbf{a}_3\rangle  & \ldots \\
0                & 0                                       & \langle\mathbf{e}_3,\mathbf{a}_3\rangle                          & \ldots \\
\vdots           & \vdots                                  & \vdots                                    & \ddots \end{pmatrix}.
$$

# Example

## from wiki

Consider the decomposition of
$$
A = 
\begin{pmatrix}
12 & -51 & 4 \\
6 & 167 & -68 \\
-4 & 24 & -41
\end{pmatrix}
$$

Recall that an orthonormal matrix Q has the property


\begin{matrix}
 Q^T \,Q = I.
\end{matrix}
Then, we can calculate Q by means of Gram–Schmidt as follows:

$$U = 
\begin{pmatrix}
\mathbf u_1 & \mathbf u_2 & \mathbf u_3
\end{pmatrix}
=
\begin{pmatrix}
12 & -69 & -58/5 \\
6  & 158 & 6/5 \\
-4 &  30 & -33
\end{pmatrix};
$$

$$
Q = 
\begin{pmatrix}
\frac{\mathbf u_1}{\|\mathbf u_1\|} &
\frac{\mathbf u_2}{\|\mathbf u_2\|} &
\frac{\mathbf u_3}{\|\mathbf u_3\|}
\end{pmatrix}
=
\begin{pmatrix}
     6/7    &    -69/175   &   -58/175   \\
     3/7    &    158/175   &     6/175   \\
    -2/7    &      6/35    &   -33/35
\end{pmatrix}.
$$

Thus, we have

\begin{matrix}
 Q^{T} A = Q^{T}Q\,R = R;
\end{matrix}

$$
\begin{matrix}
 R = Q^{T}A =
\end{matrix}
\begin{pmatrix}
    14  &  21          &            -14 \\
     0  & 175          &           -70 \\
     0  &   0          &           35
\end{pmatrix}.
$$

## Code

In [7]:
import numpy as np
import numpy.linalg as la
A = np.array([[12, -51, 4],[6,167,-68],[-4,24,-41]])
A

array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])

In [49]:
Q = np.zeros(A.shape,dtype=float)
for k in range(A.shape[1]):
    avec = A[:, k]
    q = avec
    for j in range(k):
        q = q - np.dot(avec, Q[:,j])*Q[:,j]
    qq = q*1./la.norm(q)
    qq = qq.reshape(1,-1)
    Q[:, k] = qq
print('Q:\n',Q)
R = Q.T @ A
print('R:\n', R)

Q:
 [[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]
R:
 [[  1.40000000e+01   2.10000000e+01  -1.40000000e+01]
 [ -6.66133815e-16   1.75000000e+02  -7.00000000e+01]
 [ -1.33226763e-15  -1.77635684e-14   3.50000000e+01]]
