In [17]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

import random as rnd
import os
import math

# required for interactive plotting
from __future__ import print_function
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import numpy.polynomial as np_poly

from IPython.display import Math
from IPython.display import Latex
from IPython.display import HTML

from pprint import pprint

initialization  
$ \newcommand{\E}[1]{\mathbb{E}\left[#1\right]}$  
$ \newcommand{\V}[1]{\mathbb{V}\left[#1\right]}$
$ \newcommand{\cov}[1]{\text{cov} \sigma\left[#1\right]}$
$ \newcommand{\EXP}[1]{\exp\left(#1\right)}$  
$ \newcommand{\P}{\mathbb{P}}$
$\newcommand{\mat}[1]{
\left[
\begin{matrix}
#1
\end{matrix}
\right]
}$
$\newcommand{\commentgray}[1]{\color{gray}{\text{#1}}}$

$\newcommand{\arrthree}[1]{
\begin{array}{rlr}
#1
\end{array}
}
$

sum, product
$
\newcommand{\sumiN}{\displaystyle \sum_{i=1}^{N}}
\newcommand{\sumjD}{\displaystyle \sum_{j=1}^{D}}
\newcommand{\sumjK}{\displaystyle \sum_{j=1}^{K}}
\newcommand{\sumkK}{\displaystyle \sum_{k=1}^{K}}
\newcommand{\sumkM}{\displaystyle \sum_{k=1}^{M}}
\newcommand{\summN}{\displaystyle \sum_{m=1}^{N}}
\newcommand{\sumnN}{\displaystyle \sum_{n=1}^{N}}
$
$
\newcommand{\prodjK}{\displaystyle \prod_{j=1}^{K}}
\newcommand{\prodkK}{\displaystyle \prod_{k=1}^{K}}
\newcommand{\prodmN}{\displaystyle \prod_{m=1}^{N}}
\newcommand{\prodnN}{\displaystyle \prod_{n=1}^{N}}
$

alphabet bold,
$
\newcommand{\Nl}[3]{\mathcal{N}\left(#1 \mid #2, #3\right)}
\newcommand{\Nstdx}{\Nl{\mathbf{x}}{\mathbf{\mu}}{\Sigma}}
\newcommand{\ab}{\mathbf{a}}
\newcommand{\Ab}{\mathbf{A}}
\newcommand{\Abt}{\Ab^T}
\newcommand{\Abjk}{\Ab_{jk}}
\newcommand{\bb}{\mathbf{b}}
\newcommand{\Bb}{\mathbf{B}}
\newcommand{\Cb}{\mathbf{C}}
\newcommand{\Db}{\mathbf{D}}
\newcommand{\Hb}{\mathbf{H}}
\newcommand{\Lb}{\mathbf{L}}
\newcommand{\Lbi}{\Lb^{-1}}
\newcommand{\mb}{\mathbf{m}}
\newcommand{\Mb}{\mathbf{M}}
\newcommand{\Qb}{\mathbf{Q}}
\newcommand{\Rb}{\mathbf{R}}
\newcommand{\ub}{\mathbf{u}}
\newcommand{\Xb}{\mathbf{X}}
\newcommand{\Xt}{\Xb^T}
\newcommand{\xb}{\mathbf{x}}
\newcommand{\xbm}{\xb_m}
\newcommand{\xbn}{\xb_n}
\newcommand{\xab}{\mathbf{x_a}}
\newcommand{\xabt}{\mathbf{x_a}^T}
\newcommand{\xbb}{\mathbf{x_b}}
\newcommand{\xbbt}{\mathbf{x_b}^T}
\newcommand{\yb}{\mathbf{y}}
\newcommand{\yt}{\yb^T}
\newcommand{\zb}{\mathbf{z}}
\newcommand{\zbm}{\zb_m}
\newcommand{\zbn}{\zb_n}
\newcommand{\zbnp}{\zb_{n-1}}
\newcommand{\znk}{\zb_{nk}}
\newcommand{\znpj}{\zb_{n-1,j}}
\newcommand{\Zb}{\mathbf{Z}}
\newcommand{\Ub}{\mathbf{U}}
$

math bold
$
\newcommand{\chib}{\boldsymbol{\chi}}
\newcommand{\etab}{\pmb{\eta}}
\newcommand{\etat}{\eta^T}
\newcommand{\etabt}{\etab^T}
\newcommand{\laa}{\Lambda_{aa}}
\newcommand{\laai}{\Lambda_{aa}^{-1}}
\newcommand{\lab}{\Lambda_{ab}}
\newcommand{\lba}{\Lambda_{ba}}
\newcommand{\lbb}{\Lambda_{bb}}
\newcommand{\lbbi}{\Lambda_{bb}^{-1}}
\newcommand{\li}{\Lambda^{-1}}
\newcommand{\mub}{\pmb{\mu}}
\newcommand{\muab}{\pmb{\mu}_a}
\newcommand{\mubb}{\pmb{\mu}_b}
\newcommand{\pib}{\pmb{\pi}}
\newcommand{\saa}{\Sigma_{aa}}
\newcommand{\sab}{\Sigma_{ab}}
\newcommand{\sba}{\Sigma_{ba}}
\newcommand{\sbb}{\Sigma_{bb}}
\newcommand{\thetab}{\pmb{\theta}}
\newcommand{\thetat}{\thetab^T}
\newcommand{\thetabh}{\hat{\thetab}}
\newcommand{\thetaold}{\thetab^{\text{old}}}
$

$
\newcommand{\E}[1]{\mathbb{E}\left[ #1 \right]}
\newcommand{\underl}[1]{\text{$\underline{#1}$}}
$

aliases for distributions
$\newcommand{\multivarcoeff}{\frac{1}{(2\pi)^{D/2}}
\frac{1}{\left| \mathbf{\Sigma}\right|^{1/2}}}$
$\newcommand{\multivarexp}[2]
{
\left\{
 -\frac{1}{2} 
 {#1}^T 
 #2
 {#1}
\right\}
}$
$\newcommand{\multivarexpx}[1]{\multivarexp{#1}{\Sigma^{-1}}}$
$\newcommand{\multivarexpstd}{\multivarexpx{(\xb-\mub)}}$
$\newcommand{\gam}{\operatorname{Gam}}$
$
\newcommand{\sumkMl}{\sum_{k=1}^{M-1}}
\newcommand{\sumjMl}{\sum_{j=1}^{M-1}}
$

* Inputs: covariates, predictors, features
* Outputs: variates, labels


Linear methods:  
* lotta processes can be approximates with linear models
* Linear regression: module of larger systems
* can be solved analytically

Notation
===========

* n instances of input-output pairs $\{\xb_{1:n}, \yb_{1:n} \}$
* $\xb_i \in \mathbb{R}^{d}$, that is d-dimensional
* $\yb_i \in \mathbb{R}$

Given a training set, learn the model of how inputs affect outputs.  
given a new $x_{n+1}$, find $\hat{y}(\xb_{n+1})$

* The training phase involves learning the parameters of the model $\hat{\thetab}$
* the prediction phase involves predicting $\hat{y}_{n+1}$ for a new value $\xb_{n+1}$ using the learning parameters $\hat{\thetab}$

$$
\arrthree{
\hat{y}(\xb_i) &= \theta_1 + x_i \theta_2 = \hat{y}_i
\\
J(\thetab) &=
\sumiN \left( y_i - \hat{y}_i \right)^2
\\ &=
\sumiN \left( y_i - \theta_1 - x_i \theta_2 \right)^2
}
$$



$$
\arrthree{
J: & \text{objective, cost, loss, energy, error} \\
\theta_1:& \text{y-intercept} \\
\theta_2:& \text{slope}
}
$$

if the line resembles a rod and each point is connected to the line using a spring (vertical). if we let go of the rod at any orientation, the rod will oscillate and stabilize at a particular angle. this corresponds at the minimum energy configuration

* there will always be a statistical error and there will always be uncertainty. we have to reduce this uncertainty

when does this fail  
* the line doesn't go thro any of the points.
* points in a vertical line
* points follow a high order polynomial
* outliers: will pull the rod towards, increasing the error at other points

$$
\arrthree{
i &= 1,2,\cdots,N \\
j &= 1,2,\cdots,D \\
\hat{y}_i &= \sumjD x_{ij} \theta_j
}
$$

* $x_{i1}=1$, hence $\theta_1$ corresponds to the intercept of the line with the vertical axis.  
* $\theta_1$: bias, offset :: controls the vertical distance from the origin
* $\theta_2$: controls the slope of the line

Matrix form
=============

$$
\mat{\hat{y}_1 \\ \vdots \\ \hat{y}_N}
=
\mat{
  x_{11} & \cdots & x_{1D} \\
  \vdots & \ddots & \vdots \\
  x_{N1} & \cdots & x_{ND}
}
\mat{
  \theta_1 \\
  \vdots \\
  \theta_D
}
=
\mat{
  \underl{x}_1^T \\
  \underl{x}_2^T \\
  \vdots \\
  \underl{x}_N^T
}
\mat{
  \theta_1 \\
  \vdots \\
  \theta_D
}
$$

That is,
$$
\arrthree{
\hat{\yb} &= \Xb \thetab \\
\hat{\yb} & \in \mathbb{R}^N \\
\hat{\Xb} & \in \mathbb{R}^{N \times D} \\
\hat{\thetab} & \in \mathbb{R}^D \\
}
$$

the first col of **X** is composed of 1's

In [23]:
y = np.matrix((5,25,22,18)).transpose()
X = np.matrix(((1,100,2),
               (1,50,42),
               (1,45,31),
               (1,60,35)))
print("y=")
pprint(y)
print("X=")
pprint(X)

T = np.matrix((1,0,0.5)).transpose()
print("T=")
pprint(T)

y_hat = X*T
print("y_hat= X * T = ")
pprint(y_hat)


y=
matrix([[ 5],
        [25],
        [22],
        [18]])
X=
matrix([[  1, 100,   2],
        [  1,  50,  42],
        [  1,  45,  31],
        [  1,  60,  35]])
T=
matrix([[ 1. ],
        [ 0. ],
        [ 0.5]])
y_hat= X * T = 
matrix([[  2. ],
        [ 22. ],
        [ 16.5],
        [ 18.5]])


Optimization approach
======================

$$
J(\thetab)
=
\sumiN \left( y_i - \xb_i^T \thetab \right)^2
=
\left( \yb - \Xb\thetab \right)^T
\left( \yb - \Xb\thetab \right)
$$

* contour plot: point in a single contour plot have the same function value
* gradient is always perpendicular to the contour plot

finding the minimum
--------------------

$$
\frac{\partial J(\thetab)}{\partial \theta_j}
=
\sumiN 2(y_i - \xb_{i}^{T} \thetab) (-x_{ij})
$$

We have to equate this to zero and find the values of every parameter. quite painful you see

finding the min, the easy way
------------------------------

$$
J(\thetab) = \left( \yb - \Xb \thetab \right)^T \left( \yb - \Xb \thetab \right)
$$

Results from matrix differentiation..
$$
\arrthree{
\frac{\partial \Ab \thetab}{\partial \thetab}
&=
\Abt
\\
\frac{\partial \thetat \Ab \thetab}{\partial \thetab}
&=
2 \Abt \thetab
}
$$

Thus,
$$
\arrthree{
\frac{\partial J(\thetab)}{\partial \thetab}
&= 2 \left(\yb - \Xb \thetab \right)^T
    \left( -\Xb \right)
\\
&=
2 \left( \Xb \thetab - \yb \right)^T \Xb
}
$$

The little long way
$$
\arrthree{
\frac{\partial J(\thetab)}{\partial \thetab}
&=
\frac{\partial}{\partial \thetab}
\left[
  \yt \yb - \yt \Xb \thetab - \thetat \Xt \yb 
  + \thetat \Xt \Xb \thetab
\right]
\\
&= -\Xt \yb - \Xt \yb + 2\Xt \Xb \thetab
\\
&= -2 \Xt \yb + 2\Xt \Xb \thetab
}
$$

Normal equations
------------------

Equating the derivative to zero, we get
$$
\arrthree{
\Xt \Xb \thetab &= \Xt \yb\\
\thetabh &= \left( \Xt \Xb \right)^{-1} \Xt \yb
}
$$

This equation is called the normal equations and $\thetabh$ is called the least squares estimate

$$
\hat{\yb} = \Xb \thetabh
= \Xb \left( \Xt \Xb \right)^{-1} \Xt \yb
= \Hb \yb
$$

$\Hb = \Xb \left( \Xt \Xb \right)^{-1} \Xt$ is called the hat matrix

Multiple outputs
==================

aka Multivariate linear regression


$$
\mat{
  \hat{y}_{11} & \hat{y}_{12} \\
  \vdots       & \vdots       \\
  \hat{y}_{N1} & \hat{y}_{N2} \\
}
=
\mat{
  \underl{x}_1^T \\
  \underl{x}_2^T \\
  \vdots \\
  \underl{x}_N^T
}
\mat{
  \theta_{11} & \theta_{12} \\
  \vdots      & \vdots      \\
  \theta_{D1} & \theta_{D2}
}
$$